name: CI for spectec

on:
  push:
    branches: [ main ]
    paths: [ spectec/** ]

  pull_request:
    branches: [ main ]
    paths: [ spectec/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  spec-tec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: 9.2
      - name: Setup Lean
        uses: engineerd/configurator@v0.0.9
        with:
          name: Lean
          url: https://github.com/leanprover/lean4-nightly/releases/download/nightly-2023-02-10/lean-4.0.0-nightly-2023-02-10-linux.tar.zst
          pathInArchive: lean-4.0.0-nightly-2023-02-10-linux/bin/lean
      - name: Setup Dune
        run: opam install --yes dune menhir mdx
      - name: Setup Latex
        run: sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
      - name: Setup Sphinx
        run: pip install six && pip install sphinx==5.1.0
      - name: Build and test
        run: cd spectec && opam exec make ci
